--- 
abstract: Yet Another Session Handling Library
author: 
  - Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.68
license: artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: AxKit-XSP-Minisession
no_index: 
  directory: 
    - inc
    - t
requires: 
  Apache::Cookie: 0
  Apache::Log: 0
  Apache::Session::File: 0
  AxKit: 1.62
  mod_perl: 0
  perl: 5.8.0
tests: t/*.t
version: 1.10000
