# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AxKit-XSP-Minisession
version:      1.06
version_from: lib\AxKit\XSP\Minisession.pm
installdirs:  site
requires:
    Apache::Cookie:                
    Apache::Log:                   
    Apache::Session::File:         
    AxKit:                         

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
